### ISSUE TITLE
Media control callback

### ISSUE THREAD

**Issue by perneky** [Keboo/PebbleSharp#3]
Hello,

I am using a Pebble Steel with 2.8.1FW. The WPF based demo works perfectly, but when I wanted to test the media callback (set a now playing item on the media tab, going to the Music app on the watch, and press any button), the SerialPortDataReceived function isn't called.

Is it supposed to work, or do I have to do something to make it work?

It seems the lib is not even getting a message about it.

Great project so far.

Laszlo

**Comment by Keboo** [comment]
Please re-test with the latest commit. I have also added a command line application. Using firmware v2.8.1 on my watch it is sending the media control messages.
